name: Deploy # Workflow 이름
on: # Github Actions 감지
  push:
    branches:
      - master # master branch의 Actions(push) 감지
jobs: # Github Actions 감지 후 할 일
  AUTO_DEPLOY:
    runs-on: ubuntu-latest # 최신 버전 ubuntu에서 실행됨
    
    steps:
      - name: Checkout Code # 레포지터리 체크아웃
        uses: actions/checkout@v2

      #- name: Install SSH key
      #  uses: appleboy/ssh-action@master
      #  with:
      #    password: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Generate Environment Variables File for Production
        run: |
          echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> .env.production
          echo "REACT_APP_KAKAO_REST_API_KEY=$REACT_APP_KAKAO_REST_API_KEY" >> .env.production
          echo "REACT_APP_NAVER_CLIENT_ID=$REACT_APP_NAVER_CLIENT_ID" >> .env.production
          echo "REACT_APP_NAVER_CLIENT_SECRET=$REACT_APP_NAVER_CLIENT_SECRET" >> .env.production
          echo "DB_HOST_NAME=$DB_HOST_NAME" >> .env.production
          echo "DB_HOST_USERNAME=$DB_HOST_USERNAME" >> .env.production
          echo "DB_NAME=$DB_NAME" >> .env.production
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env.production
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          REACT_APP_KAKAO_REST_API_KEY: ${{ secrets.REACT_APP_KAKAO_REST_API_KEY }}
          REACT_APP_NAVER_CLIENT_ID: ${{ secrets.REACT_APP_NAVER_CLIENT_ID }}
          REACT_APP_NAVER_CLIENT_SECRET: ${{ secrets.REACT_APP_NAVER_CLIENT_SECRET }}
          DB_HOST_NAME: ${{ secrets.DB_HOST_NAME }}
          DB_HOST_USERNAME: ${{ secrets.DB_HOST_USERNAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            pm2 delete 0
            cd ~/BusanCulture/backend
            git pull
            npm install
            pm2 start npm -- start
            exit